#!/bin/sh
DAEMON="ubi"

start() {
	printf "Starting $DAEMON: "
	/usr/sbin/ubiattach /dev/ubi_ctrl -m 0 && mount /mnt/ubi && \
	echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping $DAEMON: "
	echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
