#!/bin/sh
DAEMON="qmqmonitor"
PLATFORM=linuxfb
PROG="/usr/bin/qmqmonitor"
PIDFILE="/var/run/qmqmonitor.pid"
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

start() {
	printf "Starting $DAEMON: "
	start-stop-daemon --start --quiet --background -m -p $PIDFILE \
		--exec $PROG -- --platform $PLATFORM \
		&& echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping $DAEMON: "
	start-stop-daemon --stop --quiet -p $PIDFILE \
		&& echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
